Update extract function
Based on oh-my-zsh extract plugin by Sorin Ionescu.

diff --git a/zsh/functions/extract b/zsh/functions/extract
--- a/zsh/functions/extract
+++ b/zsh/functions/extract
@@ -1,20 +1,43 @@
-if [[ -f $1 ]]; then
-    case $1 in
-        *.tar.bz2) tar xvjf $1;;
-        *.tar.gz) tar xvzf $1;;
-        *.tar.xz) tar xvJf $1;;
-        *.tar.lzma) tar --lzma -xvf $1;;
-        *.bz2) bunzip $1;;
-        *.rar) unrar $1;;
-        *.gz) gunzip $1;;
-        *.tar) tar xvf $1;;
-        *.tbz2) tar xvjf $1;;
-        *.tgz) tar xvzf $1;;
-        *.zip) unzip $1;;
-        *.Z) uncompress $1;;
-        *.7z) 7z x $1;;
-        *) echo "'$1' cannot be extracted via >extract<";;
+local file_name
+local extract_dir
+
+while (( $# > 0 )); do
+    if [[ ! -f "$1" ]]; then
+        echo "extract: '$1' is not a valid file" 1>&2
+        shift
+        continue
+    fi
+
+    file_name="$( basename "$1" )"
+    extract_dir=${1%.*}
+
+    case "$1" in
+        (*.tar.gz|*.tgz) tar xvzf "$1" ;;
+        (*.tar.bz2|*.tbz|*.tbz2) tar xvjf "$1" ;;
+        (*.tar.xz|*.txz) tar --xz --help &> /dev/null && tar --xz -xvf "$1" \
+            || xzcat "$1" | tar xvf - ;;
+        (*.tar.zma|*.tlz) tar --lzma --help &> /dev/null && tar --lzma -xvf "$1" \
+            || lzcat "$1" | tar xvf - ;;
+        (*.tar) tar xvf "$1" ;;
+        (*.gz) gunzip "$1" ;;
+        (*.bz2) bunzip2 "$1" ;;
+        (*.xz) unxz "$1" ;;
+        (*.lzma) unlzma "$1" ;;
+        (*.Z) uncompress "$1" ;;
+        (*.zip) unzip "$1" -d $extract_dir ;;
+        (*.rar) unrar e -ad "$1" ;;
+        (*.7z) 7za x "$1" ;;
+        (*.deb)
+            mkdir -p "$extract_dir/control"
+            mkdir -p "$extract_dir/data"
+            cd "$extract_dir"; ar vx "../${1}" > /dev/null
+            cd control; tar xzvf ../control.tar.gz
+            cd ../data; tar xzvf ../data.tar.gz
+            cd ..; rm *.tar.gz debian-binary
+            cd ..
+            ;;
+        (*) echo "extract: '$1' cannot be extracted" 1>&2 ;;
     esac
-else
-    echo "'$1' is not a valid file"
-fi
+
+    shift
+done
